# Generated by Django 4.2.1 on 2023-05-23 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_login_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='DOB',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='login',
            name='MailID',
            field=models.EmailField(default='abc@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='login',
            name='Password',
            field=models.TextField(default='57***', max_length=10),
        ),
        migrations.AddField(
            model_name='login',
            name='PhnNo',
            field=models.BigIntegerField(default=0),
        ),
    ]
