# Generated by Django 4.2.1 on 2023-05-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0003_login_dob_login_mailid_login_password_login_phnno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
